# Generated by Django 5.2.6 on 2025-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("cost", models.IntegerField()),
                ("damage", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Оружие",
                "verbose_name_plural": "Оружия",
            },
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
