# Generated by Django 5.2.6 on 2025-10-11 16:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dice", "0002_weapon_delete_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weapon",
            options={
                "ordering": ["weapon_type__name", "name"],
                "verbose_name": "Оружие",
                "verbose_name_plural": "Оружия",
            },
        ),
        migrations.RemoveField(
            model_name="weapon",
            name="cost",
        ),
        migrations.AlterField(
            model_name="weapon",
            name="damage",
            field=models.CharField(
                help_text="Описание урона (например, '1d8 slashing' или '35')", max_length=50, verbose_name="Урон"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Уникальный идентификатор оружия",
                primary_key=True,
                serialize=False,
                verbose_name="ID оружия",
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="name",
            field=models.CharField(help_text="Название оружия", max_length=150, verbose_name="Имя оружия"),
        ),
        migrations.CreateModel(
            name="ArmorType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Уникальный идентификатор вида доспеха",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID вида",
                    ),
                ),
                ("name", models.CharField(help_text="Название вида доспеха", max_length=100, verbose_name="Имя вида")),
            ],
            options={
                "verbose_name": "Вид доспеха",
                "verbose_name_plural": "Виды доспеха",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["id"], name="armor_type_id_idx")],
            },
        ),
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Уникальный идентификатор доспеха",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID доспеха",
                    ),
                ),
                ("name", models.CharField(help_text="Название доспеха", max_length=150, verbose_name="Имя доспеха")),
                (
                    "armor_class",
                    models.CharField(
                        help_text="Класс/тип защиты (например, 'light', 'medium', 'heavy' или числовой показатель)",
                        max_length=50,
                        verbose_name="Класс доспеха",
                    ),
                ),
                (
                    "armor_type",
                    models.ForeignKey(
                        help_text="Категория/вид доспеха",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="armors",
                        to="dice.armortype",
                        verbose_name="Вид доспеха",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доспех",
                "verbose_name_plural": "Доспехи",
                "ordering": ["armor_type__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeaponType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Уникальный идентификатор вида оружия",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID вида",
                    ),
                ),
                ("name", models.CharField(help_text="Название вида оружия", max_length=100, verbose_name="Имя вида")),
            ],
            options={
                "verbose_name": "Вид оружия",
                "verbose_name_plural": "Виды оружия",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["id"], name="weapon_type_id_idx")],
            },
        ),
        migrations.AddField(
            model_name="weapon",
            name="weapon_type",
            field=models.ForeignKey(
                default=0,
                help_text="Категория/вид оружия",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="weapons",
                to="dice.weapontype",
                verbose_name="Вид оружия",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="weapon",
            index=models.Index(fields=["id"], name="weapon_id_idx"),
        ),
        migrations.AddIndex(
            model_name="armor",
            index=models.Index(fields=["id"], name="armor_id_idx"),
        ),
    ]
