# docker-compose.prod.yml
version: '3.8'

services:
    web:
      build:
        context: .
        target: final
      ports:
        - "10810:8000"
      volumes:
        - ./staticfiles:/app/staticfiles
        - ./db.sqlite3:/app/db.sqlite3
        - ./media:/app/media
      environment:
        - DEBUG=0
        - ALLOWED_HOSTS=192.168.170.40
        - SECRET_KEY=ваш_надежный_секретный_ключ
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
        interval: 30s
        timeout: 10s
        retries: 3
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "2"
      deploy:
        resources:
          limits:
            memory: 300M
            cpus: '0.5'
  
  nginx:
    image: nginx:alpine
    ports:
      - "10811:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
